### ISSUE TITLE
[1.8-2.1.2] Bug report on startup in 1.8 pack

### ISSUE THREAD

**Issue by Lythom** [TeamC4/Talismans2#5]
Talisman 2 1.8-2.1.2 crashes the client on startup.

Here is the full crash log

```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  FMLPlugin (InventoryTweaks-1.59-176.jar)
  NowWithRendering (redstonepaste-mc1.8-1.7.1.jar)
  VeinMinerCorePlugin (VeinMiner-1.8_0.27.0.unknown.jar)
  CCLCorePlugin (CodeChickenLib-1.8-1.1.2.133-universal.jar)
  BetterFoliageLoader (BetterFoliage-mc1.8-1.1.6.jar)
  CodeChickenCorePlugin (CodeChickenCore-1.8-1.0.5.36-universal.jar)
  CCCDeobfPlugin (unknown)
  CoreMod (Aroma1997Core-1.8-1.0.3.4.jar)
  NowWithRendering (hopperducts-mc1.8-1.4.5.jar)
  NEICorePlugin (NotEnoughItems-1.8-1.0.5.104-universal.jar)
  BOPLoadingPlugin (BiomesOPlenty-1.8-3.0.0.1099-universal.jar)
Contact their authors BEFORE contacting forge

// On the bright side, I bought you a teddy bear!

Time: 03/09/15 21:16
Description: Initializing game

java.lang.NullPointerException: Initializing game
    at Talismans2.module.bloodmagic.BloodItems.registerRender(BloodItems.java:73)
    at Talismans2.module.bloodmagic.BloodItems.registerRenders(BloodItems.java:61)
    at Talismans2.proxies.ClientProxy.registerRender(ClientProxy.java:33)
    at Talismans2.Talismans2.postinit(Talismans2.java:85)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:537)
    at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
    at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:736)
    at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:316)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:492)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:325)
    at net.minecraft.client.main.Main.main(SourceFile:120)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
    at Talismans2.module.bloodmagic.BloodItems.registerRender(BloodItems.java:73)
    at Talismans2.module.bloodmagic.BloodItems.registerRenders(BloodItems.java:61)
    at Talismans2.proxies.ClientProxy.registerRender(ClientProxy.java:33)
    at Talismans2.Talismans2.postinit(Talismans2.java:85)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:537)
    at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
    at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:736)
    at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:316)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:492)

-- Initialization --
Details:
Stacktrace:
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:325)
    at net.minecraft.client.main.Main.main(SourceFile:120)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.8
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 730151872 bytes (696 MB) / 1764753408 bytes (1683 MB) up to 3817865216 bytes (3641 MB)
    JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -Xms256m -XX:PermSize=256m
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.10 FML v8.0.99.99 Minecraft Forge 11.14.3.1512 56 mods loaded, 56 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJ   mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
    UCHIJ   FML{8.0.99.99} [Forge Mod Loader] (forge-1.8-11.14.3.1512.jar) 
    UCHIJ   Forge{11.14.3.1512} [Minecraft Forge] (forge-1.8-11.14.3.1512.jar) 
    UCHIJ   Aroma1997Core{1.0.3.4} [Aroma1997Core] (Aroma1997Core-1.8-1.0.3.4.jar) 
    UCHIJ   CodeChickenCore{1.0.5.36} [CodeChicken Core] (minecraft.jar) 
    UCHIJ   NotEnoughItems{1.0.5.104} [Not Enough Items] (NotEnoughItems-1.8-1.0.5.104-universal.jar) 
    UCHIJ   VeinMiner_coremod{0.26.1_build.unknown} [Core mod] (minecraft.jar) 
    UCHIJ   BiomesOPlenty{3.0.0} [Biomes O' Plenty] (BiomesOPlenty-1.8-3.0.0.1099-universal.jar) 
    UCHIJ   arrowcam{1.1} [Arrow Camera] (1.8_arrowcam_v1.2.jar) 
    UCHIJ   securitycraft{v1.7.4.1} [SecurityCraft] ([1.8] SecurityCraft v1.7.4.1.jar) 
    UCHIJ   bspkrsCore{7.01} [bspkrsCore] ([1.8]bspkrsCore-universal-7.01.jar) 
    UCHIJ   ArmorStatusHUD{1.8} [ArmorStatusHUD] ([1.8]ArmorStatusHUD-client-1.29.jar) 
    UCHIJ   CrystalWing{1.8.r01} [CrystalWing] ([1.8]CrystalWing-universal-1.8.r01.jar) 
    UCHIJ   StatusEffectHUD{1.8} [StatusEffectHUD] ([1.8]StatusEffectHUD-client-1.27.jar) 
    UCHIJ   animalbikes{1.8} [Animal Bikes] (AnimalBikes_1.8.0.jar) 
    UCHIJ   antiqueatlas{4.2.7-1.8} [Antique Atlas] (antiqueatlas-4.2.7-1.8.jar) 
    UCHIJ   Aroma1997CoreHelper{1.0.3.4} [Aroma1997Core|Helper] (Aroma1997Core-1.8-1.0.3.4.jar) 
    UCHIJ   AromaBackup{0.0.1.0} [AromaBackup] (AromaBackup-1.8-0.0.1.0.jar) 
    UCHIJ   iChunUtil{5.4.0} [iChunUtil] (iChunUtil-5.4.0.jar) 
    UCHIJ   BackTools{5.1.0} [BackTools] (BackTools-5.1.0.jar) 
    UCHIJ   Baubles{1.1.1.0} [Baubles] (Baubles-1.8-1.1.1.0.jar) 
    UCHIJ   BetterFoliage{1.1.6} [Better Foliage] (BetterFoliage-mc1.8-1.1.6.jar) 
    UCHIJ   AWWayofTime{v1.3.3} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.8-1.4.0-1.jar) 
    UCHIJ   C4Lib{1.0.0} [C4Lib] (C4Lib-1.8-1.0.0-universal.jar) 
    UCHIJ   capsule{1.0.1} [Capsule] (capsule-1.8-1.0.1.jar) 
    UCHIJ   Chameleon{1.8-0.1.0} [Chameleon] (Chameleon-1.8-0.1.0.jar) 
    UCHIJ   chisel{@VERSION@} [Chisel 3] (Chisel_DEV-MC1.8-0.0.1.3.jar) 
    UCHIJ   customnpcs{1.8.0_beta} [CustomNPCs] (CustomNPCs_1.8.0_beta.jar) 
    UCHIJ   cyclopscore{0.1.1} [Cyclops Core] (CyclopsCore-1.8-0.1.1.jar) 
    UCHIJ   evilcraft{0.8.1} [EvilCraft] (EvilCraft-1.8-0.8.1.jar) 
    UCHIJ   HelpFixer{1.1.9} [HelpFixer] (HelpFixer-1.1.9.jar) 
    UCHIJ   hopperducts{1.4.5} [Hopper Ducts] (hopperducts-mc1.8-1.4.5.jar) 
    UCHIJ   InfernalMobs{1.6.4} [Infernal Mobs] (InfernalMobs-1.8.jar) 
    UCHIJ   InventoryPets{Beta} [Inventory Pets] (inventorypets-1.8-beta.jar) 
    UCHIJ   inventorytweaks{1.59-176-9318a76-dirty} [Inventory Tweaks] (InventoryTweaks-1.59-176.jar) 
    UCHIJ   IronChest{6.0.99.749} [Iron Chest] (ironchest-1.8-6.0.99.749-universal.jar) 
    UCHIJ   lootplusplus{1.1.1_for_1.8} [Loot++] (Loot++-1.1.1_for_1.8.jar) 
    UCHIJ   RadixCore{1.8-2.0.5} [RadixCore] (RadixCore-1.8-2.0.5-universal.jar) 
    UCHIJ   MCA{1.8-5.0.7.1} [Minecraft Comes Alive] (MCA-1.8-5.0.7.1-universal.jar) 
    UCHIJ   moreplayermodels{1.8.0_beta} [MorePlayerModels] (MorePlayerModels_1.8.0_beta.jar) 
    UCHIJ   pandorasbox{2.1.2} [Pandora's Box] (PandorasBox-2.1.2.jar) 
    UCHIJ   parachutemod{3.1.1} [Parachute Mod] (parachutemod-1.8.0-3.1.2-96.jar) 
    UCHIJ   progressiveautomation{1.6.15} [Progressive Automation] (ProgressiveAutomation-1.8-1.6.15.jar) 
    UCHIJ   quickhotbar{1.04} [Quick Hotbar] (quickhotbar_18_1.04.jar) 
    UCHIJ   ragdollCorpses{0.12} [Ragdoll Corpses] (ragdollCorpses-0.12 for 1.8.jar) 
    UCHIJ   redstonepaste{1.7.1} [Redstone Paste] (redstonepaste-mc1.8-1.7.1.jar) 
    UCHIJ   Roguelike{1.3.6} [Roguelike Dungeons] (RoguelikeDungeons-1.8-1.3.6.jar) 
    UCHIJ   soundfilters{0.8_for_1.8} [Sound Filters] (SoundFilters-0.8_for_1.8.jar) 
    UCHIJ   StorageDrawers{1.8-2.1.9} [Storage Drawers] (StorageDrawers-1.8-2.1.9.jar) 
    UCHIE   Talismans 2{2.1.2} [Talismans 2] (Talismans2-1.8-2.1.2.jar) 
    UCHIJ   ultimate_unicorn_mod{1.2.2} [Wings, Horns, and Hooves, the Ultimate Unicorn Mod!] (ultimate_unicorn_mod-1.8-1.2.2.jar) 
    UCHIJ   VeinMiner{0.26.1_build.unknown} [Vein Miner] (VeinMiner-1.8_0.27.0.unknown.jar) 
    UCHIJ   VeinMinerModSupport{0.26.1_build.unknown} [Mod Support] (VeinMiner-1.8_0.27.0.unknown.jar) 
    UCHIJ   Waila{1.6.0_B1} [Waila] (Waila-1.6.0_B1_1.8.1.jar) 
    UCHIJ   wailafeatures{0.0.1} [WAILA Features] (WAILA-features-1.8-0.0.1.jar) 
    UCHIJ   denseores{1.0} [denseores] (denseores-2.(-1).0 (alpha 1.8).jar) 
    Loaded coremods (and transformers): 
FMLPlugin (InventoryTweaks-1.59-176.jar)
  invtweaks.forge.asm.ContainerTransformer
NowWithRendering (redstonepaste-mc1.8-1.7.1.jar)
  net.fybertech.nwr.NowWithRendering
VeinMinerCorePlugin (VeinMiner-1.8_0.27.0.unknown.jar)
  portablejim.veinminer.asm.ItemInWorldManagerTransformer
CCLCorePlugin (CodeChickenLib-1.8-1.1.2.133-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.RenderHookTransformer
BetterFoliageLoader (BetterFoliage-mc1.8-1.1.6.jar)
  mods.betterfoliage.loader.impl.BetterFoliageTransformer
CodeChickenCorePlugin (CodeChickenCore-1.8-1.0.5.36-universal.jar)
  codechicken.core.asm.InterfaceDependancyTransformer
  codechicken.core.asm.TweakTransformer
  codechicken.core.asm.DelegatedTransformer
  codechicken.core.asm.DefaultImplementationTransformer
CCCDeobfPlugin (unknown)

CoreMod (Aroma1997Core-1.8-1.0.3.4.jar)

NowWithRendering (hopperducts-mc1.8-1.4.5.jar)
  net.fybertech.nwr.NowWithRendering
NEICorePlugin (NotEnoughItems-1.8-1.0.5.104-universal.jar)
  codechicken.nei.asm.NEITransformer
BOPLoadingPlugin (BiomesOPlenty-1.8-3.0.0.1099-universal.jar)
  org.spongepowered.asm.mixin.transformer.MixinTransformer
    GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 347.52' Renderer: 'GeForce GTX 560 Ti/PCIe/SSE2'
    Launched Version: forge-11.14.3.1512
    LWJGL: 2.9.1
    OpenGL: GeForce GTX 560 Ti/PCIe/SSE2 GL version 4.5.0 NVIDIA 347.52, NVIDIA Corporation
    GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

    Using VBOs: No
    Is Modded: Definitely; Client brand changed to 'fml,forge'
    Type: Client (map_client.txt)
    Resource Packs: []
    Current Language: English (US)
    Profiler Position: N/A (disabled)
```

**Comment by gigabit101** [comment]
Didn't know that blood magic was out for 1.8 yet and I havant ported that module yet will fix tonight

**Comment by Lythom** [comment]
Blood Magic is in alpha for 1.8 and doesn't work yet either (https://github.com/WayofTime/BloodMagic/issues/443).
No need to rush the fix, but thank you for your great reactivity !

**Comment by gigabit101** [comment]
new version has been uploaded to CurseForge http://minecraft.curseforge.com/mc-mods/224434-talismans-2/files
